#!/bin/bash
echo "Welcome to the FreeViewing Experiment - to generate the tsv-logger-forms, please provide subject and session numbers"
read -p "Subject-Number:" sub
read -p "Session-Number:" ses

# convert to number
sub=$((sub))
ses=$((ses))


sub=$(printf "%03d" $sub)
ses=$(printf "%03d" $ses)
cd "$(dirname "${BASH_SOURCE[0]}")"
cd ..
mkdir -p "data/sub-$sub/ses-$ses/beh"
cp --target-directory="data/sub-$sub/ses-$ses/beh" assets/template-labnotebook.tsv assets/template-participantform.tsv
mv "data/sub-$sub/ses-$ses/beh/template-labnotebook.tsv" "data/sub-$sub/ses-$ses/beh/sub-${sub}_ses-${ses}_labnotebook.tsv"
mv "data/sub-$sub/ses-$ses/beh/template-participantform.tsv" "data/sub-$sub/ses-$ses/beh/sub-${sub}_ses-${ses}_participantform.tsv"
gedit "data/sub-$sub/ses-$ses/beh/sub-${sub}_ses-${ses}_participantform.tsv"
gedit "data/sub-$sub/ses-$ses/beh/sub-${sub}_ses-${ses}_labnotebook.tsv"
