#!/bin/bash
cd ..
mkdir -p "data/sub-$1/ses-$2/beh"
cp --target-directory="data/sub-$1/ses-$2/beh" assets/template-labnotebook.tsv assets/template-participantform.tsv
mv "data/sub-$1/ses-$2/beh/template-labnotebook.tsv" "data/sub-$1/ses-$2/beh/sub-$1_ses-$2_labnotebook.tsv"
mv "data/sub-$1/ses-$2/beh/template-participantform.tsv" "data/sub-$1/ses-$2/beh/sub-$1_ses-$2_participantform.tsv"
gedit "data/sub-$1/ses-$2/beh/sub-$1_ses-$2_participantform.tsv"
gedit "data/sub-$1/ses-$2/beh/sub-$1_ses-$2_labnotebook.tsv"
